obstacle_range: 3
raytrace_range: 3.5
footprint: [[.271, -0.253], [.271, .253], [-0.143, .253], [-0.143, -0.253]]
#robot_radius: ir_of_robot
inflation_radius: 0.2

transform_tolerance: 0.5

observation_sources: laser_scan_sensor

laser_scan_sensor:
  {
    sensor_frame: laser,
    data_type: LaserScan,
    topic: /scan,
    marking: true,
    clearing: true,
  }

# point_cloud_sensor:
#   {
#     sensor_frame: frame_name,
#     data_type: PointCloud,
#     topic: topic_name,
#     marking: true,
#     clearing: true,
#   }

map_topic: /map
subscribe_to_updates: true
update_frequency: 5.0
publish_frequency: 5.0

plugins:
  - {name: static_layer, type: "costmap_2d::StaticLayer"}
  - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

static_layer:
  map_topic: /map
  subscribe_to_updates: false

obstacle_layer:
    observation_sources: laser_scan_sensor
    laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}