obstacle_range: 3
raytrace_range: 3.5
footprint: [[.271, -0.253], [.271, .253], [-0.143, .253], [-0.143, -0.253]]
#robot_radius: ir_of_robot
inflation_radius: 0.55

transform_tolerance: 0.5

observation_sources: laser_scan_sensor

laser_scan_sensor:
  {
    sensor_frame: laser,
    data_type: LaserScan,
    topic: /scan,
    marking: true,
    clearing: true,
  }

# point_cloud_sensor:
#   {
#     sensor_frame: frame_name,
#     data_type: PointCloud,
#     topic: topic_name,
#     marking: true,
#     clearing: true,
#   }
