global_costmap:
  global_frame: map
  robot_base_frame: base_link
  static_map: true
  subscribe_to_updates: true
  update_frequency: 5.0
  publish_frequency: 5.0

  plugins:
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

  static_layer:
    map_topic: /map
    subscribe_to_updates: false

  obstacle_layer:
      observation_sources: laser_scan_sensor
      laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}